# NAV-LOSEN MVP - SUPABASE CONFIGURATION
# Created: 20. oktober 2025
# Author: Manus (Agent #6)

[api]
# API settings
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# Database settings
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
# Realtime settings (for live updates)
enabled = true
ip_version = "ipv4"

[studio]
# Supabase Studio settings
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
# Email testing (local development)
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# Storage settings (for file uploads)
enabled = true
file_size_limit = "50MiB"

[auth]
# Auth settings
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://navlosen.netlify.app"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
# Email auth settings
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
# Google OAuth (optional)
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.external.apple]
# Apple OAuth (optional)
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:54321/auth/v1/callback"

[analytics]
# Analytics settings
enabled = false

