# Netlify configuration for NAV-Losen Frontend
# Deployed for Mobile Simulator iframe integration

[build]
  command = "npm run build"
  publish = ".next"

# Use Netlify Next.js plugin for optimal deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

# CORS headers for iframe embedding in web-console
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"

# No redirects needed - Next.js handles routing

