name: Sync Learning Points to Notion (SLL)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-lp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Sync LP to Notion (SMK sources)
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          SLL_DATABASE_ID: ${{ secrets.SLL_DATABASE_ID }}
        run: |
          python scripts/parse_lp.py

      - name: Report results
        if: always()
        run: |
          echo "✅ Learning Points sync workflow completed (SMK → SLL)"
